name: Flutter CI

on:
  pull_request: # calls action on pull request
    branches: [ dev ] # calls action on master branch

env:
  flutter_version: "1.20.4"
  java_version: "12.x"

jobs:
  format-and-lint:
    name: formatting and code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: flutter format lib/
      - name: Lint analysis
        run: flutter analyze --no-pub
