name: Close Pull Request On Markdowns

on:
  pull_request:
    types: [opened]
    path:
      - '*.md'

jobs:
  close-md-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v2
      with:
        comment: "We do not accept PRs to the markdown files. If you have any questions, please feel free to contact us."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
